# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

SUBDIRS += lib \
           server \
           shell

CONFIG += release warn_on ordered
TEMPLATE = subdirs

